packages:
  universal:
    apts:
      - zsh
      - tmux
      - fd-find
      - git
      - curl
      - wget
      - vim
      - jq
      - python3
      - python3-venv
      - snapd
      - tree
      - htop
      - gnupg2
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - libssl-dev
      - unzip
      - figlet
      - ripgrep
      - lolcat
      - whiptail
      - bat
      - zoxide
      - direnv
    snap:
      - bw
      - yazi --classic
    npm_packages:
      - "@google/gemini-cli"