packages:
  universal:
    apts:
      - build-essential
      - zsh
      - tmux
      - fd-find
      - git
      - curl
      - wget
      - vim
      - jq
      - snapd
      - tree
      - htop
      - gnupg2
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - libssl-dev
      - unzip
      - figlet
      - ripgrep
      - lolcat
      - whiptail
      - bat
      - zoxide
      - direnv
    snap:
      - bw
      - yazi --classic
    npm_packages:
      - "@google/gemini-cli"
  python_dev:
    apts:
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - python3-venv
      - python3-wheel
      # code quality tools
      - black
      - python3-isort
      - python3-mypy
      - pylint
    uv:
      - ruff
      - poetry